/*
 * accelGyro.h
 *
 *  Created on: Sep 1, 2024
 *      Author: sargs
 */

#pragma once

#include "main.h"

#define LSM_REG_FUNC_CFG_ACCESS 0x01
#define LSM_REG_SENSOR_SYNC_TIME_FRAME 0x04
#define LSM_REG_FIFO_CTRL1 0x06
#define LSM_REG_FIFO_CTRL2 0x07
#define LSM_REG_FIFO_CTRL3 0x08
#define LSM_REG_FIFO_CTRL4 0x09
#define LSM_REG_FIFO_CTRL5 0x0A
#define LSM_REG_ORIENT_CFG_G 0x0B
#define LSM_REG_INT1_CTRL 0x0D
#define LSM_REG_INT2_CTRL 0x0E
#define LSM_REG_WHO_AM_I 0x0F
#define LSM_REG_CTRL1_XL 0x10
#define LSM_REG_CTRL2_G 0x11
#define LSM_REG_CTRL3_C 0x12
#define LSM_REG_CTRL4_C 0x13
#define LSM_REG_CTRL5_C 0x14
#define LSM_REG_CTRL6_C 0x15
#define LSM_REG_CTRL7_G 0x16
#define LSM_REG_CTRL8_XL 0x17
#define LSM_REG_CTRL9_XL 0x18
#define LSM_REG_CTRL10_C 0x19
#define LSM_REG_MASTER_CONFIG 0x1A
#define LSM_REG_WAKE_UP_SRC 0x1B
#define LSM_REG_TAP_SRC 0x1C
#define LSM_REG_D6D_SRC 0x1D
#define LSM_REG_STATUS_REG 0x1E
#define LSM_REG_OUT_TEMP_L 0x20
#define LSM_REG_OUT_TEMP_H 0x21
#define LSM_REG_OUTX_L_G 0x22
#define LSM_REG_OUTX_H_G 0x23
#define LSM_REG_OUTY_L_G 0x24
#define LSM_REG_OUTY_H_G 0x25
#define LSM_REG_OUTZ_L_G 0x26
#define LSM_REG_OUTZ_H_G 0x27
#define LSM_REG_OUTX_L_XL 0x28
#define LSM_REG_OUTX_H_XL 0x29
#define LSM_REG_OUTY_L_XL 0x2A
#define LSM_REG_OUTY_H_XL 0x2B
#define LSM_REG_OUTZ_L_XL 0x2C
#define LSM_REG_OUTZ_H_XL 0x2D
#define LSM_REG_SENSORHUB1 0x2E
#define LSM_REG_SENSORHUB2 0x2F
#define LSM_REG_SENSORHUB3 0x30
#define LSM_REG_SENSORHUB4 0x31
#define LSM_REG_SENSORHUB5 0x32
#define LSM_REG_SENSORHUB6 0x33
#define LSM_REG_SENSORHUB7 0x34
#define LSM_REG_SENSORHUB8 0x35
#define LSM_REG_SENSORHUB9 0x36
#define LSM_REG_SENSORHUB10 0x37
#define LSM_REG_SENSORHUB11 0x38
#define LSM_REG_SENSORHUB12 0x39
#define LSM_REG_FIFO_STATUS1 0x3A
#define LSM_REG_FIFO_STATUS2 0x3B
#define LSM_REG_FIFO_STATUS3 0x3C
#define LSM_REG_FIFO_STATUS4 0x3D
#define LSM_REG_FIFO_DATA_OUT_L 0x3E
#define LSM_REG_FIFO_DATA_OUT_H 0x3F
#define LSM_REG_TIMESTAMP0 0x40
#define LSM_REG_TIMESTAMP1 0x41
#define LSM_REG_TIMESTAMP2 0x42
#define LSM_REG_STEP_TIMESTAMP_L 0x49
#define LSM_REG_STEP_TIMESTAMP_H 0x4A
#define LSM_REG_STEP_COUNTER_L 0x4B
#define LSM_REG_STEP_COUNTER_H 0x4C
#define LSM_REG_SENSORHUB13_REG 0x4D
#define LSM_REG_SENSORHUB14_REG 0x4E
#define LSM_REG_SENSORHUB15_REG 0x4F
#define LSM_REG_SENSORHUB16_REG 0x50
#define LSM_REG_SENSORHUB17_REG 0x51
#define LSM_REG_SENSORHUB18_REG 0x52
#define LSM_REG_FUNC_SRC 0x53
#define LSM_REG_TAP_CFG 0x58
#define LSM_REG_TAP_THS_6D 0x59
#define LSM_REG_INT_DUR2 0x5A
#define LSM_REG_WAKE_UP_THS 0x5B
#define LSM_REG_WAKE_UP_DUR 0x5C
#define LSM_REG_FREE_FALL 0x5D
#define LSM_REG_MD1_CFG 0x5E
#define LSM_REG_MD2_CFG 0x5F
#define LSM_REG_OUT_MAG_RAW_X_L 0x66
#define LSM_REG_OUT_MAG_RAW_X_H 0x67
#define LSM_REG_OUT_MAG_RAW_Y_L 0x68
#define LSM_REG_OUT_MAG_RAW_Y_H 0x69
#define LSM_REG_OUT_MAG_RAW_Z_L 0x6A
#define LSM_REG_OUT_MAG_RAW_Z_H 0x6B


#define LSM_SET_WHO_AM_I_VAL 0x6A
#define LSM_SET_OPER_MODE 0b10000100
#define LSM_SET_GYRO_MODE 0b011
#define LSM_SET_CTRL3_C 0b01000100



uint8_t LSM_Init(SPI_HandleTypeDef *hspi, GPIO_TypeDef *port, uint16_t pin);
void LSM_ReadData(int16_t endBufer[]);
